package com.cursojava04.modulo4.solid;

public class Empleado {
	//IMPLEMENTAR RESPONSABILIDAD UNICA
	//LA CLASE TIENE QUE HACER UNA SOLA COSA
	//SI LA CLASE HACE MAS DE UNA CLASE ES QUE HACER MAS CLASES
	
	public void calcularSueldo() {
		//LOGICA DE CALCULO DE SUELDO
	}
	
	//ESTE METODO LE DA OTRA RESPONSABILIDAD A LA CLASE
	//Y ES QUE REFACTORIZAR CREANDOLO EN OTRA CLASE
//	public void guardarDatos() {
//		// LOGICA GUARDAR DATOS EN BD DE UN EMPLEADO
//	}

}
